apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: playground
  name: playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playground
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: playground
    spec:
      containers:
      - command:
        - tail
        - -f
        - /dev/null
        image: alpine:latest
        name: alpine
        resources: 
          requests:
            cpu: 100m
            memory: 100m
          limits:
            cpu: 100m
            memory: 100m
status: {}
